# Generated by Django 4.0 on 2022-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='object_type',
            field=models.CharField(choices=[('Milestone', 'Milestone'), ('Issue', 'Issue'), ('Project', 'Project'), ('Pull request', 'Pull request'), ('Label', 'Label'), ('Assignees', 'Assignees'), ('Changes', 'Changes'), ('Comments', 'Comments'), ('Approved', 'Approved'), ('Merged', 'Merged')], default='Changes', max_length=20),
        ),
    ]
