# Generated by Django 4.0 on 2021-12-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=20)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='user.user')),
                ('developers', models.ManyToManyField(related_name='user_developers', to='user.User')),
            ],
        ),
    ]
