# Generated by Django 4.0 on 2022-01-28 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='forks',
            field=models.ManyToManyField(related_name='user_forks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='stargazers',
            field=models.ManyToManyField(related_name='user_stargazers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='watchers',
            field=models.ManyToManyField(related_name='user_watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
