# Generated by Django 4.0 on 2021-12-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('repository', '0002_repository_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
