# Generated by Django 4.0 on 2022-01-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_alter_milestone_status'),
        ('repository', '0002_alter_repository_creator_alter_repository_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='milestones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='milestone.milestone'),
        ),
    ]
