# Generated by Django 4.0 on 2022-01-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_repository_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='milestones',
        ),
    ]
