# Generated by Django 4.0 on 2021-12-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('repository', '0003_repository_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='developers',
            field=models.ManyToManyField(related_name='user_developers', to='user.User'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to='user.user'),
        ),
    ]
