# Generated by Django 3.2.9 on 2022-01-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
        ),
    ]
