# Generated by Django 4.0 on 2022-01-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_name'),
        ('branch', '0002_initial'),
    ]

    operations = [
    ]
