# Generated by Django 4.0 on 2022-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('&#129505', '&#129505'), ('&#128640', '&#128640'), ('&#128577', '&#128577'), ('&#128512', '&#128512'), ('&#128077', '&#128077'), ('&#128077', '&#128077')], default='&#129505', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='emoji',
            field=models.ManyToManyField(to='comment.Emoji'),
        ),
    ]
