# Generated by Django 4.0 on 2022-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_emoji_comment_created_date_comment_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.CharField(choices=[('129505', '129505'), ('128640', '128640'), ('128577', '128577'), ('128512', '128512'), ('128077', '128077'), ('128077', '128077')], default='129505', max_length=20),
        ),
    ]
