# Generated by Django 4.0 on 2022-01-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comment', '0003_alter_emoji_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emoji',
            new_name='emojis',
        ),
        migrations.AddField(
            model_name='emoji',
            name='reaction_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
