# Generated by Django 4.0 on 2022-01-28 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0005_alter_emoji_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='reaction_creator',
        ),
        migrations.AddField(
            model_name='emoji',
            name='reaction_creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
