# Generated by Django 4.0 on 2022-01-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_remove_emoji_reaction_creator_emoji_reaction_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emoji',
            old_name='reaction_creator',
            new_name='reaction_creators',
        ),
    ]
