# Generated by Django 4.0 on 2021-12-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('comment', '0001_initial'),
        ('pullrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='comments',
            field=models.ManyToManyField(to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_branch', to='branch.branch'),
        ),
    ]
