# Generated by Django 3.2.9 on 2022-01-30 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pullrequest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='reviewers',
            field=models.ManyToManyField(related_name='pullrequest_reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
