# Generated by Django 4.0 on 2022-01-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('pullrequest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='history',
            field=models.ManyToManyField(to='history.History'),
        ),
    ]
