# Generated by Django 3.2.9 on 2022-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullrequest', '0003_pullrequest_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
