# Generated by Django 4.0 on 2022-02-01 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('label', '0002_initial'),
        ('milestone', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pullrequest', '0004_pullrequest_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='assignees',
            field=models.ManyToManyField(related_name='pull_request_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='labels',
            field=models.ManyToManyField(to='label.Label'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='milestone',
            field=models.ManyToManyField(to='milestone.Milestone'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='projects',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
