# Generated by Django 4.0 on 2022-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Authenticate user', 'Authenticate user'), ('Unauthenticate user', 'Unauthenticate user')], default='Unauthenticate user', max_length=20)),
            ],
        ),
    ]
