# Generated by Django 4.0 on 2022-01-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
