# Generated by Django 4.0 on 2021-12-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='issue_title',
        ),
    ]
