# Generated by Django 3.2.9 on 2022-02-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
