# Generated by Django 4.0 on 2021-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullrequest', '0001_initial'),
        ('issue', '0002_rename_title_issue_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pullrequests',
            field=models.ManyToManyField(to='pullrequest.Pullrequest'),
        ),
    ]
