# Generated by Django 4.0 on 2022-01-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_milestone'),
        ('issue', '0003_initial'),
    ]

    operations = [
    ]
