# Generated by Django 4.0 on 2021-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Close', 'Close')], default='Close', max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
