# Generated by Django 4.0 on 2022-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened', max_length=20),
        ),
    ]
