# Generated by Django 4.0 on 2021-12-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='dueDate',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
