# Generated by Django 4.0 on 2021-12-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_rename_duedate_milestone_due_date_milestone_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Closed', max_length=20),
        ),
    ]
