# Generated by Django 4.0 on 2022-01-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(default=' ', max_length=50)),
                ('opened', models.DateField(auto_now_add=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('assigned', models.ManyToManyField(to='user.User')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.user')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestone.milestone')),
            ],
        ),
    ]
