# Generated by Django 4.0 on 2021-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(to='user.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
