name: Django CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd Uks
        python manage.py test branch.tests --noinput
        python manage.py test comment.tests --noinput
        python manage.py test commit.tests --noinput
        python manage.py test home.tests --noinput
        python manage.py test insights.tests --noinput
        python manage.py test issue.tests --noinput
        python manage.py test label.tests --noinput
        python manage.py test milestone.tests --noinput
        python manage.py test project.tests --noinput
        python manage.py test pullrequest.tests --noinput
        python manage.py test repository.tests --noinput
        python manage.py test user.tests --noinput

